name: kisankonnect
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  sqflite: ^1.3.0
  path_provider: any
  progress_dialog: ^1.2.4
  http: 0.12.1
  archive: 2.0.13
  pin_code_fields: 3.1.2
  flutter_form_builder: 3.10.1
  rxdart: 0.24.1
  geolocator: ^5.3.2+2
  shared_preferences: 0.5.7+3
  connectivity: 0.4.8+6
  flushbar: ^1.10.4
  app_settings: 4.0.1+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  gen_lang: 0.1.3

flutter:
  uses-material-design: true
  fonts:
    - family: Proxima
      fonts:
        - asset: assets/fonts/proxima_nova.ttf
  assets:
    - assets/
    - graphics/